// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwhgtqxdfccyzhmgqntt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3aGd0cXhkZmNjeXpobWdxbnR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NzQ0ODAsImV4cCI6MjA2ODI1MDQ4MH0.-Mge20bT1UaaGI6yESOgRHqGjV8xOhTvIumFATY7OAY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});